"""
pdf_report.py
Generates a downloadable PDF report for a single prediction.
Requires: pip install fpdf2
"""

from fpdf import FPDF
from datetime import datetime
import os

DISCLAIMER = "This is general information, please consult a doctor."


def _safe(text):
    """
    fpdf2's core Helvetica font only supports latin-1. Smart quotes, em/en
    dashes, arrows, emoji, etc. (easy to end up with from copy-pasted text
    or f-string formatting) can otherwise make fpdf2 miscompute available
    line width and crash with 'Not enough horizontal space to render a
    single character'. Replacing anything outside latin-1 keeps this safe.
    """
    return str(text).encode("latin-1", "replace").decode("latin-1")


class MediPredictPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(11, 70, 69)  # teal-deep
        self.cell(0, 10, _safe("MediPredict - Health Risk Report"), ln=True, align="C")
        self.set_draw_color(220, 232, 229)  # line color
        self.line(10, 20, 200, 20)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(75, 100, 97)  # ink-soft
        self.cell(0, 10, _safe(f"Generated by MediPredict on {datetime.now().strftime('%d %b %Y, %I:%M %p')}"),
                   align="C")


def generate_pdf_report(user_name, disease, prediction, confidence, tips,
                         input_data, output_path=None):
    """
    user_name: str
    disease: str (display name, e.g. "Diabetes")
    prediction: int (0 or 1)
    confidence: float (0-100)
    tips: list[str]
    input_data: dict of {field_name: value} shown in the report
    output_path: where to save; defaults to reports/<disease>_<timestamp>.pdf
    """
    pdf = MediPredictPDF()
    pdf.add_page()

    safe_width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(14, 43, 42)  # ink
    pdf.cell(0, 8, _safe(f"Patient: {user_name}"), ln=True)
    pdf.cell(0, 8, _safe(f"Disease Screened: {disease}"), ln=True)
    pdf.ln(4)

    # Result box
    result_text = "HIGH RISK" if prediction == 1 else "LOW RISK"
    pdf.set_font("Helvetica", "B", 14)
    if prediction == 1:
        pdf.set_text_color(217, 96, 63)  # coral
    else:
        pdf.set_text_color(46, 155, 107)  # green
    pdf.cell(0, 10, _safe(f"Result: {result_text}  (Confidence: {confidence}%)"), ln=True)
    pdf.set_text_color(14, 43, 42)
    pdf.ln(4)

    # Input values table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Input Values", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for field, value in input_data.items():
        pdf.cell(0, 7, _safe(f"  {field}: {value}"), ln=True)
    pdf.ln(4)

    # Suggestions
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Suggestions", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for tip in tips:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(safe_width, 7, _safe(f"  - {tip}"))
    pdf.ln(4)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(75, 100, 97)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(safe_width, 6, _safe(DISCLAIMER))

    if output_path is None:
        reports_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "reports")
        os.makedirs(reports_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = os.path.join(reports_dir, f"{disease.lower().replace(' ', '_')}_{timestamp}.pdf")

    pdf.output(output_path)
    return output_path


if __name__ == "__main__":
    path = generate_pdf_report(
        user_name="Test User",
        disease="Diabetes",
        prediction=1,
        confidence=82.5,
        tips=["Monitor blood glucose levels regularly.", "Reduce sugar intake."],
        input_data={"Glucose": 150, "BMI": 29.4, "Age": 45},
    )
    print("Saved:", path)
